// <auto-generated />
using Divibot.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Divibot.Migrations {

    [DbContext(typeof(DivibotDbContext))]
    partial class DivibotDbContextModelSnapshot : ModelSnapshot {

        protected override void BuildModel(ModelBuilder modelBuilder) {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("Relational:MaxIdentifierLength", 64)
                        .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("Divibot.Database.Entities.EntityAfkUser", b => {
                b.Property<ulong>("UserId").ValueGeneratedOnAdd().HasColumnType("bigint unsigned");
                b.Property<string>("Message").HasColumnType("longtext");
                b.HasKey("UserId");
                b.ToTable("AfkUsers");
            });

            modelBuilder.Entity("Divibot.Database.Entities.EntityVersion", b => {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<int>("Commands").HasColumnType("int");
                b.Property<int>("Launches").HasColumnType("int");
                b.Property<int>("MajorVersion").HasColumnType("int");
                b.Property<int>("MinorVersion").HasColumnType("int");
                b.HasKey("Id");
                b.ToTable("Versions");
            });
#pragma warning restore 612, 618
        }

    }

}
